### PR TITLE
Make DockerRemoteApi plugin configuration cache compatible for Gradle 8.1+

### LINKED ISSUE #1192: Starting/Stopping docker daemon invalidates Gradle configuration cache
### Current Behavior
The file /var/run/docker.sock is saved as a file system entry to the configuration cache. 
When starting or stopping the Docker daemon, this file changes and causes the configuration cache being invalidated.

### Expected Behavior
Configuration cache state should not be affected of file changes outside of the project

### Steps to Reproduce (for bugs)
Attached zip file contain minimal test project and a README.md file
[reproduce-config-cache-docker-sock.zip](https://github.com/bmuschko/gradle-docker-plugin/files/12559840/reproduce-config-cache-docker-sock.zip)

### Your Environment
Linux

### PR DESCRIPTION
**Pull request by Jocce-Nilsson**
Using Gradle 8.1 or above will make Gradle gather information on file access during configuration time. If any of those files change until next time you run Gradle, the configuration cache is invalidated.

This PR delays the file checking for default value of the DockerExtension so that the files are not part of configuration cache input.

closes #1192

### CODE REVIEW

File: src/docTest/groovy/com/bmuschko/gradle/docker/RemoteApiPluginDocumentationTest.groovy [hunk 1]
```diff
@@ -117,6 +118,7 @@ HEALTHCHECK CMD wget --quiet --tries=1 --spider http://localhost:8080/actuator/h
         dsl << ALL_DSLS
     }
 
+    @Ignore("Getting error: Task :pullImage FAILED")
```
Comment (pbielicki) [inline src/docTest/groovy/com/bmuschko/gradle/docker/RemoteApiPluginDocumentationTest.groovy:121]: ⭕ shouldn't this be unignored?

File: src/functTest/groovy/com/bmuschko/gradle/docker/AbstractFunctionalTest.groovy [hunk 2]
```diff
@@ -20,6 +20,7 @@ abstract class AbstractFunctionalTest extends Specification {
     File buildFile
     File settingsFile
     Map<String, String> envVars = new HashMap<>()
+    String version = null
```
Comment (pbielicki) [inline src/functTest/groovy/com/bmuschko/gradle/docker/AbstractFunctionalTest.groovy:23]: ⭕ let's use a consistent syntax here, wdyt?
```suggestion
    String version
```

File: src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy [hunk 3]
```diff
@@ -261,6 +261,38 @@ class DockerRemoteApiPluginFunctionalTest extends AbstractGroovyDslFunctionalTes
...
+    def "configuration cache compatible when docker state changes on disk for OS #osName"() {
+        given:
+        useGradleVersion("8.3")
+
+        and:
+        // Force use of user.home and define a variable holding the file
+        def home = new File(temporaryFolder, "home").tap{it.mkdirs()}
+        def dockerSockDirectory = new File(home, "/.docker/run/").tap{it.mkdirs()}
+        String[] arguments = [
+            "-Dcom.bmuschko.gradle.docker.internal.DefaultDockerUrlValueSource.skipCheckOfVarRun=true",
```
Comment (pbielicki) [inline src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy:274]: ⭕ please extract a const - it's used in at least three places

File: src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerSaveImageFunctionalTest.groovy [hunk 4]
```diff
@@ -4,13 +4,15 @@ import com.bmuschko.gradle.docker.AbstractGroovyDslFunctionalTest
...
 import org.gradle.testkit.runner.BuildResult
+import spock.lang.Ignore
 import spock.lang.Unroll
 
 import static org.gradle.testkit.runner.TaskOutcome.FAILED
 import static org.gradle.testkit.runner.TaskOutcome.SKIPPED
 import static org.gradle.testkit.runner.TaskOutcome.SUCCESS
 import static org.gradle.testkit.runner.TaskOutcome.UP_TO_DATE
 
+@Ignore("Getting error: Task :pullImage FAILED")
```
Comment (pbielicki) [inline src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerSaveImageFunctionalTest.groovy:15]: ⭕ unignore?

File: src/test/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocatorTest.groovy [hunk 5]
```diff
@@ -121,6 +122,7 @@ class RegistryAuthLocatorTest extends Specification {
         0 * logger.error(*_)
     }
 
+    @Ignore("I get 0 invocations of 'logger.error(*_)'")
```
Comment (pbielicki) [inline src/test/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocatorTest.groovy:125]: ⭕ unignore?

**Review by pbielicki — APPROVED** [review]
nice work 🎉

File: src/docTest/groovy/com/bmuschko/gradle/docker/RemoteApiPluginDocumentationTest.groovy (hunk 1 above)
Comment (Jocce-Nilsson) [reply src/docTest/groovy/com/bmuschko/gradle/docker/RemoteApiPluginDocumentationTest.groovy]: done

File: src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy [hunk 6]
```diff
@@ -261,6 +261,38 @@ class DockerRemoteApiPluginFunctionalTest extends AbstractGroovyDslFunctionalTes
...
+            "-Duser.home=${home.absolutePath}",
+            "-Dos.name=$osName",
+            "help"
+        ].toArray()
```
[the remark this answers is not in the document]
Comment (Jocce-Nilsson) [reply src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy:278]: No, I'm forcing the array to not be Object[] by using String[]

File: src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerSaveImageFunctionalTest.groovy (hunk 4 above)
Comment (Jocce-Nilsson) [reply src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerSaveImageFunctionalTest.groovy]: done

File: src/test/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocatorTest.groovy (hunk 5 above)
Comment (Jocce-Nilsson) [reply src/test/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocatorTest.groovy]: done

File: src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy (hunk 3 above)
Comment (Jocce-Nilsson) [reply src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy:274]: the thing is, I do not want to expose it. It is used in 2 places, one in the test and one in the class

File: src/main/java/com/bmuschko/gradle/docker/internal/DefaultDockerUrlValueSource.java [hunk 7]
```diff
@@ -0,0 +1,52 @@
...
+                //Added for possibility to run integration tests, also makes it possible to override use of /var/run/
+                boolean skipVarRun = Boolean.valueOf(System.getProperty("com.bmuschko.gradle.docker.internal.DefaultDockerUrlValueSource.skipCheckOfVarRun", "false"));
+                // macOS or Linux
+                if (isFileExists("/var/run/docker.sock") && !skipVarRun) {
+                    dockerUrl = "unix:///var/run/docker.sock";
+                } else if (isFileExists(System.getProperty("user.home") + "/.docker/run/docker.sock")) {
+                    dockerUrl = "unix://" + System.getProperty("user.home") + "/.docker/run/docker.sock";
+                }
+            }
+
```
[the remark this answers is not in the document]
Comment (Jocce-Nilsson) [reply src/main/java/com/bmuschko/gradle/docker/internal/DefaultDockerUrlValueSource.java:33]: copied lines from original code, keeping for comparison

File: src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy [hunk 8]
```diff
@@ -261,6 +261,38 @@ class DockerRemoteApiPluginFunctionalTest extends AbstractGroovyDslFunctionalTes
         build('convert')
     }
 
+
+    def "configuration cache compatible when docker state changes on disk for OS #osName"() {
```
Comment (bmuschko) [inline src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy:265]: This test method should define a precondition for the operating system.

File: src/main/java/com/bmuschko/gradle/docker/internal/DefaultDockerUrlValueSource.java [hunk 9]
```diff
@@ -0,0 +1,52 @@
...
+import org.gradle.api.logging.Logger;
+import org.gradle.api.logging.Logging;
+import org.gradle.api.provider.ValueSource;
+import org.gradle.api.provider.ValueSourceParameters;
+
+import javax.annotation.Nullable;
+import java.io.File;
+
+public abstract class DefaultDockerUrlValueSource implements ValueSource<String, ValueSourceParameters.None> {
```
Comment (bmuschko) [inline src/main/java/com/bmuschko/gradle/docker/internal/DefaultDockerUrlValueSource.java:11]: I don't think this class need to be `abstract` right? Only if you wanted to inject an object reference with `@Inject` I believe.

File: src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy (hunk 8 above)
Comment (Jocce-Nilsson) [reply src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy:265]: Can you please elaborate? I am not sure i follow. 
The reason that I added the OS was the knowledge of the implementation and that the path to be taken is only achieved by specifying OS.

File: src/main/java/com/bmuschko/gradle/docker/internal/DefaultDockerUrlValueSource.java (hunk 9 above)
Comment (Jocce-Nilsson) [reply src/main/java/com/bmuschko/gradle/docker/internal/DefaultDockerUrlValueSource.java:11]: There is a method in the interface that is documented in this way [in the Javadoc of ValueSource](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/ValueSource.html):

> Do not implement this method in your subclass. Gradle provides the implementation when creating a provider from the value source via [ProviderFactory.of(Class, Action)](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/ProviderFactory.html#of-java.lang.Class-org.gradle.api.Action-).

File: src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy (hunk 8 above)
Comment (bmuschko) [reply src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy:265]: This: `@IgnoreIf({ os.windows })`. If other developers run the test on a Windows machine, it will likely fail.

File: src/main/java/com/bmuschko/gradle/docker/internal/DefaultDockerUrlValueSource.java (hunk 9 above)
Comment (bmuschko) [reply src/main/java/com/bmuschko/gradle/docker/internal/DefaultDockerUrlValueSource.java:11]: I am still confused on when to use `abstract` or not on this class. IMHO this should be spelled out more explicitly by the documentation.

This is example uses it: https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements:external_processes.
The Javadoc shows an example that doesn't: https://docs.gradle.org/current/javadoc/org/gradle/api/provider/ValueSource.html

```
 public class MyValueSource implements ValueSource<...> {
     @Inject
     public MyValueSource(ExecOperations execOperations) {
         ...
     }
 }
```

Comment (Jocce-Nilsson) [reply src/main/java/com/bmuschko/gradle/docker/internal/DefaultDockerUrlValueSource.java:11]: It must be abstract, and the Javadoc is incorrect and will be updated, thank you!
The getParameters() implementation must be provided by Gradle.

File: src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy (hunk 8 above)
Comment (Jocce-Nilsson) [reply src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy:265]: Ah, sure!

Comment (Jocce-Nilsson) [reply src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy:266]: done

File: src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy [hunk 10]
```diff
@@ -114,7 +115,7 @@ class DockerRemoteApiPluginFunctionalTest extends AbstractGroovyDslFunctionalTes
             import com.bmuschko.gradle.docker.tasks.image.DockerPullImage
             import com.bmuschko.gradle.docker.tasks.image.DockerRemoveImage
             import com.bmuschko.gradle.docker.tasks.image.Dockerfile
-            
+
```
Comment (Jocce-Nilsson) [inline src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy:118]: auto formatting, is this OK to remove @bmuschko?

Comment (bmuschko) [reply src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy:118]: That's fine. Seem like a tab or tabs ended up here.

File: src/main/java/com/bmuschko/gradle/docker/internal/DefaultDockerUrlValueSource.java (hunk 9 above)
Comment (bmuschko) [reply src/main/java/com/bmuschko/gradle/docker/internal/DefaultDockerUrlValueSource.java:11]: Good deal.

**Review by bmuschko — APPROVED** [review]
Thanks for your pull request. I am going to release a patch soon.
