### PR TITLE
Fix custom registry in logs

### LINKED ISSUE #1090: Incorrect registry in logs when pushing images
### Expected Behavior

```
> Task :my-project:pushDockerImage
Pushing image 'registry.mycompany.com/my-image:latest' to registry.mycompany.com.
```

### Current Behavior

```
> Task :my-project:pushDockerImage
Pushing image 'registry.mycompany.com/my-image:latest' to https://index.docker.io/v1/.
```

### Context

We're seeing something in our logs that wouldn't imply the correct behavior. When pushing to a registry, the logs printed aren't using the registry parsed from the docker image url.

### Your Environment

gradle 7.5.1

### PR DESCRIPTION
**Pull request by Sineaggi**
Not 100% sure if `authConfig.registryAddress` is the correct choice for the log output, I've instead changed it to call the `getRegistry` function directly, otherwise it prints out dockerhub.

closes #1090

### CODE REVIEW

**Comment by Sineaggi** [comment]
Alternatively, perhaps the return result of `registryAddress` should contain the custom registry address, and it's the result of `lookupAuthConfig` that needs to change instead?

File: src/main/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocator.groovy [hunk 1]
```diff
@@ -281,7 +281,7 @@ class RegistryAuthLocator {
      * @param image the name of the docker image
      * @return docker registry name
      */
-    private static String getRegistry(String image) {
+    static String getRegistry(String image) {
```
Comment (bmuschko) [inline src/main/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocator.groovy:284]: This should become a non-static method. We already have the instance of `RegistryAuthLocator` in `DockerPushImage`.

File: src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy [hunk 2]
```diff
@@ -56,7 +57,7 @@ class DockerPushImage extends AbstractDockerRemoteApiTask implements RegistryCre
 
         for (String image : images.get()) {
             AuthConfig authConfig = getRegistryAuthLocator().lookupAuthConfig(image, registryCredentials)
-            logger.quiet "Pushing image '${image}' to ${authConfig.registryAddress}."
+            logger.quiet "Pushing image '${image}' to ${RegistryAuthLocator.getRegistry(image)}."
```
Comment (bmuschko) [inline src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy:60]: Should use the instance of `getRegistryAuthLocator()`.

File: src/test/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocatorTest.groovy [hunk 3]
```diff
@@ -152,6 +152,29 @@ class RegistryAuthLocatorTest extends Specification {
         0 * logger.error(*_)
     }
 
+    def "AuthLocator returns correct default registry"() {
+        given:
+        String image = 'ubuntu'
+
+        when:
+        String registry = RegistryAuthLocator.getRegistry(image)
```
Comment (bmuschko) [inline src/test/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocatorTest.groovy:160]: Shouldn't use the static method here. Use the instance instead.

File: src/test/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocatorTest.groovy [hunk 4]
```diff
@@ -152,6 +152,29 @@ class RegistryAuthLocatorTest extends Specification {
...
+        registry == 'https://index.docker.io/v1/'
+    }
+
+
+    def "AuthLocator returns correct custom registry"() {
+        given:
+        String image = 'gcr.io/distroless/java17'
+
+        when:
+        String registry = RegistryAuthLocator.getRegistry(image)
```
Comment (bmuschko) [inline src/test/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocatorTest.groovy:172]: Shouldn't use the static method here. Use the instance instead.

File: src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy (hunk 2 above)
Comment (bmuschko) [reply src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy:60]: The same logic should be used in `DockerPullImage`.

**Review by bmuschko — CHANGES_REQUESTED** [review]
Thanks for the pull request. Could you please make the changes based on my comments?

File: src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy (hunk 2 above)
Comment (Sineaggi) [reply src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy]: Is it fine to call `getRegistryAuthLocator()`, or should I pull that out to a variable locally?

File: src/test/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocatorTest.groovy (hunk 4 above)
Comment (Sineaggi) [reply src/test/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocatorTest.groovy]: Done

File: src/test/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocatorTest.groovy (hunk 3 above)
Comment (Sineaggi) [reply src/test/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocatorTest.groovy]: Done

File: src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy (hunk 2 above)
Comment (bmuschko) [reply src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy]: I'd assign it to a variable for reuse within the same class.

File: src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy [hunk 5]
```diff
@@ -56,7 +57,7 @@ class DockerPushImage extends AbstractDockerRemoteApiTask implements RegistryCre
 
         for (String image : images.get()) {
             AuthConfig authConfig = getRegistryAuthLocator().lookupAuthConfig(image, registryCredentials)
-            logger.quiet "Pushing image '${image}' to ${authConfig.registryAddress}."
+            logger.quiet "Pushing image '${image}' to ${getRegistryAuthLocator().getRegistry(image)}."
```
Comment (bmuschko) [inline src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy:60]: This is missing the `get()` call on `image`.

Comment (bmuschko) [reply src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy:60]: @Sineaggi Can you make the change? CI is failing right now. I am planning to release as soon as you make the change.

Comment (Sineaggi) [reply src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy:60]: I'm sure the code is right, the image is already a String. The test also passes while running in linux in a docker image.

Comment (bmuschko) [reply src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy:60]: Looks like the CI issue was unrelated. Thanks for checking.

**Comment by bmuschko** [comment]
Thanks for the PR. This has been merged.
