### PR TITLE
Plugin resolves and uses Docker credential helper

### LINKED ISSUE #743: dockerPushImage: Docker credential helpers don't apply
First of all, thank you for the awesome plugin! Couldn't find your patreon page though...

### Expected Behavior
`./gradlew dockerPushImage` should work on a properly tagged image (`docker push <mytag>` works fine).

### Current Behavior
`./gradlew dockerPushImage` fails with error
```
> Could not push image: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```
However, if I do `docker push gcr.io/my-project/my-image` then it works fine. Because I already followed the steps by that link above and did  `gcloud auth configure-docker`. Looks like it wrote auth tokens to gcr.io to `~/.docker/config.json`. So it seems like gradle-docker-plugin just doesn't use it.

### Context
I have the following in my gradle.build.kts:
```kotlin
tasks {
    docker {
        // https://bmuschko.github.io/gradle-docker-plugin/#java-application-plugin
        javaApplication {
            baseImage.set("openjdk:11-jre-slim")
            maintainer.set("")
            ports.set(listOf())
            tag.set("gcr.io/my-project/my-image")
        }
    }
}
```

And the following in `~/.docker/config.json`:
```json
        "credHelpers": {
                "asia.gcr.io": "gcloud",
                "eu.gcr.io": "gcloud",
                "gcr.io": "gcloud",
                "marketplace.gcr.io": "gcloud",
                "staging-k8s.gcr.io": "gcloud",
                "us.gcr.io": "gcloud"
        }
```

### Your Environment
id("com.bmuschko.docker-java-application") version "4.4.0"
Docker version 18.09.1, build 4c52b90
Google Cloud SDK 231.0.0

### PR DESCRIPTION
**Pull request by kgrech**
This pr closes #743.

The PR solves the problem that PushImage and PullImage build task are not able to get the credential information from the ``~/.docker/config.json`` file

### CODE REVIEW

File: src/main/groovy/com/bmuschko/gradle/docker/utils/RegistryAuthLocator.groovy [hunk 1]
```diff
@@ -0,0 +1,261 @@
...
+        log.debug('No helper found in the {} section', CREDS_STORE_SECTION)
+        return null
+    }
+
+    private static String runCommand(String hostName, String credentialHelperName) {
+        log.debug('Executing docker credential helper: {} to locate auth config for: {}',
+            credentialHelperName, hostName)
+        try {
+            ProcessBuilder pb = new ProcessBuilder(credentialHelperName, 'get')
+            Process process = pb.start()
```
Comment (cdancy) [inline src/main/groovy/com/bmuschko/gradle/docker/utils/RegistryAuthLocator.groovy]: We could probably just use [built-in groovy](https://docs.groovy-lang.org/latest/html/groovy-jdk/java/lang/String.html#execute()) to do this in a more simple way.

Comment (kgrech) [reply src/main/groovy/com/bmuschko/gradle/docker/utils/RegistryAuthLocator.groovy]: @cdancy Thanks for the suggestion, I am done with it

File: src/main/groovy/com/bmuschko/gradle/docker/DockerRegistryCredentials.groovy [hunk 2]
```diff
@@ -116,4 +116,14 @@ class DockerRegistryCredentials {
             }
         }
     }
+
+    /**
+     * Check if credentials are valid. Valid means that it has
+     * at least one of the following properties set:
+     * username, password, email
+     * @return
```
Comment (bmuschko) [inline src/main/groovy/com/bmuschko/gradle/docker/DockerRegistryCredentials.groovy]: This portion of the Javadocs doesn't actually describe the return. Needs to have a description.

File: src/main/groovy/com/bmuschko/gradle/docker/DockerRegistryCredentials.groovy [hunk 3]
```diff
@@ -116,4 +116,14 @@ class DockerRegistryCredentials {
...
+     */
+    boolean isValid() {
+        username.isPresent() || password.isPresent() || email.isPresent()
```
Comment (bmuschko) [inline src/main/groovy/com/bmuschko/gradle/docker/DockerRegistryCredentials.groovy]: I am not sure why we'd assume that credentials that only provide the email or password would be considered valid. IMHO this needs to be username and password. The email is optional.

File: src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractCredentialsAwareRemoteApiTask.groovy [hunk 4]
```diff
@@ -0,0 +1,36 @@
+package com.bmuschko.gradle.docker.tasks
+
+import com.bmuschko.gradle.docker.DockerRegistryCredentials
+import com.github.dockerjava.api.model.AuthConfig
+import groovy.transform.CompileStatic
+
+@CompileStatic
+abstract class AbstractCredentialsAwareRemoteApiTask extends AbstractDockerRemoteApiTask
```
Comment (bmuschko) [inline src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractCredentialsAwareRemoteApiTask.groovy]: Let's use delegation instead of another parent class here. Can you explain why this class was introduced? Is the only reason to have the method `resolveAuthConfig` available?

File: src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractDockerRemoteApiTask.groovy [hunk 5]
```diff
@@ -167,6 +169,17 @@ abstract class AbstractDockerRemoteApiTask extends DefaultTask {
         dockerClient
     }
 
+    /**
+     * Gets a docker-java auth config
+     * @return docker-java auth config
```
Comment (bmuschko) [inline src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractDockerRemoteApiTask.groovy]: The parameters/return are not defined correctly.

File: src/main/groovy/com/bmuschko/gradle/docker/utils/RegistryAuthLocator.groovy [hunk 6]
```diff
@@ -0,0 +1,247 @@
...
+import groovy.transform.CompileStatic
+import org.apache.commons.lang.SystemUtils
+import org.gradle.api.logging.Logger
+import org.gradle.api.logging.Logging
+
+/**
+ * Utility class to get credentials information from $DOCKER_CONFIG/.docker/config.json file
+ * Supports auth token, credentials store and credentials helpers
+ * Only linux OS is supported at the moment.
+ * Returns default auth object if called on windows
```
Comment (bmuschko) [inline src/main/groovy/com/bmuschko/gradle/docker/utils/RegistryAuthLocator.groovy]: Could you please reference the code repository you got this from as a comment to give credit?

**Comment by bmuschko** [comment]
@kgrech Trying to get a feeling if you are planning to address the review comments soon. It would be great to have the feature in the next release.

**Comment by kgrech** [comment]
@bmuschko I will work on it over weekend. The only thing I am not clear 100% is the functional test. The problem is that I need a private docker registry to access. Shall I run a new temporary docker container with the private registry? I will also need some dummy credential helper for it. 

Do you have any idea on how to implement the same simpler?

File: src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractCredentialsAwareRemoteApiTask.groovy (hunk 4 above)
Comment (kgrech) [reply src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractCredentialsAwareRemoteApiTask.groovy]: I have introduced as there are 3 classes having the same block of code, which I have added to ``resolveAuthConfig`` method. The third one is DockerBuild class, but I did not change it in scope of this PR.

I can change it to have a delegation, something like ``authConfigResolver.resolve``, but then AuthConfigResolver will need to be provided with DockerRegistryCredentials and encapsulate ``RegistryAuthLocator.groovy``. 

Maybe it is a good idea to put this method in the ``RegistryAuthLocator.groovy`` class itself. I think it is not a bad idea, just worrying that RegistryAuthLocator.groovy is getting a bit too big. What do you think?

File: src/main/groovy/com/bmuschko/gradle/docker/DockerRegistryCredentials.groovy (hunk 3 above)
Comment (kgrech) [reply src/main/groovy/com/bmuschko/gradle/docker/DockerRegistryCredentials.groovy]: I agree, will change.

But actually, the root cause of the problem is that in the `` if(registryCredentials && registryCredentials.isValid()) {`` it looks like registryCredentials is never null.

File: src/main/groovy/com/bmuschko/gradle/docker/utils/RegistryAuthLocator.groovy (hunk 6 above)
Comment (kgrech) [reply src/main/groovy/com/bmuschko/gradle/docker/utils/RegistryAuthLocator.groovy]: Done

File: src/main/groovy/com/bmuschko/gradle/docker/utils/RegistryAuthLocator.groovy [hunk 7]
```diff
@@ -0,0 +1,293 @@
+package com.bmuschko.gradle.docker.utils
+
+import com.bmuschko.gradle.docker.DockerRegistryCredentials
+import com.fasterxml.jackson.databind.JsonNode
```
Comment (bmuschko) [inline src/main/groovy/com/bmuschko/gradle/docker/utils/RegistryAuthLocator.groovy]: Instead of using Jackson, can we change this to use `JsonSlurper` instead? I don't necessarily want to depend on that library explicitly.

File: src/main/groovy/com/bmuschko/gradle/docker/utils/RegistryAuthLocator.groovy [hunk 8]
```diff
@@ -0,0 +1,293 @@
...
+import com.fasterxml.jackson.databind.ObjectMapper
+import com.github.dockerjava.api.model.AuthConfig
+import groovy.transform.CompileStatic
+import org.apache.commons.lang.SystemUtils
```
Comment (bmuschko) [inline src/main/groovy/com/bmuschko/gradle/docker/utils/RegistryAuthLocator.groovy]: This library might be pulled in by Docker Java, however, I'd like to avoid dependencies to other external libraries as much as possible. Can you maybe just inline the logic?

**Comment by bmuschko** [comment]
@kgrech Hi, just wanted get a rough idea to see if you'd be able to address the comment I left over the weekend?

**Comment by kgrech** [comment]
@bmuschko I have addressed the dependencies issue, I will work on integration test over the weekend

**Comment by kgrech** [comment]
@bmuschko Done

**Comment by bmuschko** [comment]
@kgrech Thanks for those changes. I made simplified the handling of registry credentials on `master`: https://github.com/bmuschko/gradle-docker-plugin/pull/879. Now you don't have to check anymore if those are "valid". Could you please merge `master` into your branch?

**Comment by kgrech** [comment]
@bmuschko 

Somehow when I am testing the latest version I am getting the following error:
```
A problem occurred evaluating project ':aikey-alice'.
> Failed to apply plugin [id 'com.bmuschko.docker-remote-api']
   > Could not create an instance of type com.bmuschko.gradle.docker.DockerExtension.
      > Could not create an instance of type com.bmuschko.gradle.docker.DockerRegistryCredentials.
         > The constructor for class com.bmuschko.gradle.docker.DockerRegistryCredentials should be annotated with @Inject.
```

**Comment by bmuschko** [comment]
@kgrech I added the annotation to `master` this morning. Shouldn't be working fine if you merged `master` into your branch. Tests are passing on `master`. You may want to have a look at the stack trace. What's the failing test?

**Comment by kgrech** [comment]
@bmuschko 
I have just merged master and I see it my branch.

Somehow I am getting in my test project:
```
Caused by: org.gradle.api.reflect.ObjectInstantiationException: Could not create an instance of type com.bmuschko.gradle.docker.DockerRegistryCredentials.
        at org.gradle.internal.instantiation.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:54)
        at org.gradle.api.internal.model.DefaultObjectFactory.newInstance(DefaultObjectFactory.java:82)
        at com.bmuschko.gradle.docker.DockerExtension.<init>(DockerExtension.groovy:79)
        at com.bmuschko.gradle.docker.DockerExtension_Decorated.<init>(Unknown Source)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.gradle.internal.instantiation.AsmBackedClassGenerator.newInstance(AsmBackedClassGenerator.java:179)
        at org.gradle.internal.instantiation.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:395)
        at org.gradle.internal.instantiation.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:49)
```

**Comment by kgrech** [comment]
This is my build.gradle:
```
import com.bmuschko.gradle.docker.tasks.image.DockerPushImage

buildscript {
    dependencies {
        classpath files('/home/grekon/projects/gradle-docker-plugin/build/libs/gradle-docker-plugin-5.1.1-SNAPSHOT.jar')
    }
}
apply plugin: 'com.bmuschko.docker-remote-api'

task dockerpush(type: DockerPushImage) {
	images.set(["localhost:5001/${project.name}:$version"])
}
```

**Comment by kgrech** [comment]
I see tests are also passing on my branch after the merge, but somehow my test project does not work anymore....

**Comment by bmuschko** [comment]
@kgrech I just tried a sample project and see the same issue. I am going to look at it and let you know when it's fixed.

**Comment by bmuschko** [comment]
@kgrech At the moment I have no idea why the code doesn't work. I created an issue with the Gradle team: https://github.com/gradle/gradle/issues/11152

**Comment by kgrech** [comment]
@bmuschko I see the same behaviour in master as well. Do you think this PR can get merged or would you like to wait/add morr changes here?

**Comment by bmuschko** [comment]
@kgrech Yep, it's based on my change on `master` this morning. Your PR is in a good place and ready to be merged. I just want to fix the issue we are seeing on `master` first. Will probably happen sometime next week.

**Comment by bmuschko** [comment]
@kgrech I fixed the issue on `master`. Would you mind rebasing your branch and trying it again?

**Comment by kgrech** [comment]
@bmuschko Thanks for the fix. I have merged it and can confirm that it works for my project now.

**Comment by bmuschko** [comment]
Thanks for all your work on this. Much appreciated. I will merge and make some more changes from my end.

**Comment by bmuschko** [comment]
@kgrech Looks like there's an issue with the code we integrated with this change: https://github.com/bmuschko/gradle-docker-plugin/issues/887. Would you have any time in having a deeper look?

**Comment by kgrech** [comment]
@bmuschko I will have a look over the weekend. It looks like we can bypass it changing the log level, but I think the root cause is in some missing validation during the JSON parsing, which needs to be fixed.

However, I think we can having a warning log level still would be more logical. I do not think having debug log level is a good idea as it would hide real problems with a JSON file from the user, but we should ensure it does not trow the error when the file is correct

**Comment by antonjah** [comment]
@kgrech @bmuschko Has this been fixed somewhere or do we still have this problem? I can't seem to find anything else about this :-(

**Comment by kgrech** [comment]
@antonjah what exactly is the problem? We made some changes in PR #898 related to it
