### PR TITLE
Inspec exec container

### LINKED ISSUE #361: Exit codes for TaskType:DockerExecContainer
I have tried to use this for my project, one of my requirement is to exec into a container and run a script, check for exit codes if the scripts fails(return a non-zero exit code) and fail the task. Is there a way to check exit codes for taskType:DockerExecContainer if cmd[] fails?

### PR DESCRIPTION
**Pull request by orzeh**
Adds new task DockerInspectExecContainer which allows to inspect exec instance.

This should fix #361

### CODE REVIEW

File: src/main/groovy/com/bmuschko/gradle/docker/response/container/InspectExecContainerResponseHandler.groovy [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+
+import org.gradle.api.logging.Logger
+import org.gradle.api.logging.Logging
+
+/**
+ * Logs inspect exec container result.
+ *
+ * @see com.bmuschko.gradle.docker.tasks.container.DockerInspectExecContainer
+ */
+class InspectExecContainerResponseHandler {
```
Comment (cdancy) [inline src/main/groovy/com/bmuschko/gradle/docker/response/container/InspectExecContainerResponseHandler.groovy]: I'd actually push back against adding this as I think we want to move away from using this form of callback in favor of the work you did with reactive-streams which IMO is a much better way to go about such things. Thoughts?

Comment (orzeh) [inline src/main/groovy/com/bmuschko/gradle/docker/response/container/InspectExecContainerResponseHandler.groovy]: This is just a fallback which prints result to stdout (via logger) when `onNext` is not defined. IMO it is consistent with current implementation of other tasks.

**Comment by orzeh** [comment]
@cdancy I've moved it to separate task because of two reasons:
* the _exec_ can take some time to finish
* user may not be interested in _exec_ exit code and other details at all

File: src/main/groovy/com/bmuschko/gradle/docker/response/container/InspectExecContainerResponseHandler.groovy (hunk 1 above)
Comment (cdancy) [inline src/main/groovy/com/bmuschko/gradle/docker/response/container/InspectExecContainerResponseHandler.groovy]: Just getting back around to this now. I really think we should remove this in favor of using an `onNext` block and if none is passed than create one. Within a few releases I'd like to remove any use of the "response handler" objects/concept as I believe the reactive-streams impl is a superior solution. Keeping it in, and/or adding to it, may give the wrong impression that we want to keep this around.

Aside from that: everything else looks good.

**Comment by cdancy** [comment]
Would it make sense to put this functionality within the `DockerExecContainer` task and provide some sort of hook to make it work? I know it would break our "1 task" principle but it might be worth it in this case.

File: src/main/groovy/com/bmuschko/gradle/docker/response/container/InspectExecContainerResponseHandler.groovy (hunk 1 above)
Comment (orzeh) [inline src/main/groovy/com/bmuschko/gradle/docker/response/container/InspectExecContainerResponseHandler.groovy]: ok, I'll rework this and remove _response handler_

**Comment by orzeh** [comment]
It would be hard to define nice DSL in `DockerExecContainer` task. I think it is better to have this logic separated as it is more flexible solution.

**Comment by cdancy** [comment]
@orzeh fair enough and I actually agree though I was secretly hoping you would have provided a compelling enough reason (I couldn't think of one) for us to break the "1 task" rule ;)

**Comment by orzeh** [comment]
@cdancy I've removed logging handler. Please review.

**Comment by cdancy** [comment]
All tests pass as expected. Thanks again @orzeh !

File: src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerExecContainer.groovy [hunk 2]
```diff
@@ -20,38 +20,45 @@ import org.gradle.api.tasks.Optional
...
+    Boolean attachStdout = true
 
-  	@Input
-  	@Optional
-  	Boolean attachStderr = true
+    @Input
+    @Optional
+    Boolean attachStderr = true
 
+    String execId
```
Comment (cdancy) [inline src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerExecContainer.groovy]: Just merged this PR but wondering if we should make this private and provide a method to retrieve it's value? Might give the impression that it can or should be set by developers.

Comment (orzeh) [inline src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerExecContainer.groovy]: good point, I'll fix it soon.

**Comment by seb-koch** [comment]
Is there an example on how to use this new task? Struggling to get this up and running.

**Comment by orzeh** [comment]
@seb-koch Just see [functional test](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/DockerInspectExecContainerFunctionalTest.groovy)
