### PR TITLE
Make taskPath safe for windows before using it

### LINKED ISSUE #689: IOException on DockerBuildImage Task
Running the following DockerBuildImage Task throws an IOException:

`task createDockerfile(type: Dockerfile) {
    destFile = project.file('build/Dockerfile')
    from 'ubuntu:12.04'
}

task buildDockerImage(type: DockerBuildImage) {
    dependsOn createDockerfile
    inputDir = createDockerfile.destFile.get().asFile.parentFile
    tag = 'bmuschko/myimage:latest'

}`

Stacktrace:
`org.gradle.api.UncheckedIOException: java.io.IOException: Die Syntax f├╝r den Dateinamen, Verzeichnisnamen oder die Datentr├ñgerbezeichnung ist falsch
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.canonicalizedPaths(DefaultTaskExecutionPlan.java:686)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.getOutputPaths(DefaultTaskExecutionPlan.java:770)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.resolveMutations(DefaultTaskExecutionPlan.java:611)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.getResolvedMutationInfo(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.selectNext(DefaultTaskExecutionPlan.java:552)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$2.transform(DefaultTaskPlanExecutor.java:174)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$2.transform(DefaultTaskPlanExecutor.java:161)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:161)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.io.IOException: Die Syntax f├╝r den Dateinamen, Verzeichnisnamen oder die Datentr├ñgerbezeichnung ist falsch
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.canonicalizedPaths(DefaultTaskExecutionPlan.java:681)
        ... 12 more`

I had to Debug Gradle to see whats going on here.
The exception happens in 
DefaultTaskExecutionPlan:681

Gradle tries to resolve the following path:
`F:\*******\build\.docker\:buildDockerImage-imageId.txt`
That fails with an IOException because of the ":"

### Your Environment
Gradle 4.10.2
gradle-docker-plugin 4.0.1
Windows

### PR DESCRIPTION
**Pull request by rmtmckenzie**
The BuildDockerImage task writes a file to `$buildDir/.docker/$taskpath-imageId.txt` but didn't properly sanitize the path for windows (which doesn't allow colons in file paths).

This PR adds logic to strip the first colon and replace any others with underscores.
Closes #689. 

(Just an FYI - I wasn't able to run the full suite of tests before committing as it seems they don't run on windows - lots of errors to do with paths not being supported and unix sockets. So hopefully I didn't break a bunch of tests =D )

### CODE REVIEW

File: src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy [hunk 1]
```diff
@@ -121,7 +122,9 @@ class DockerBuildImage extends AbstractDockerRemoteApiTask implements RegistryCr
 
     DockerBuildImage() {
         inputDir.set(project.file('docker'))
-        File imageIdTextFile = new File(project.buildDir, ".docker/${path}-imageId.txt")
+
+        String safeTaskPath = path.replaceFirst("^:", "").replaceAll(":", "_")
```
Comment (bmuschko) [inline src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy]: Thanks for the PR. Maybe we should just hash the task path. Might make it easier to avoid other issues in the future with Windows.

**Comment by bmuschko** [comment]
> (Just an FYI - I wasn't able to run the full suite of tests before committing as it seems they don't run on windows - lots of errors to do with paths not being supported and unix sockets. So hopefully I didn't break a bunch of tests =D )

Thanks for the info, I will have to look into that.

File: src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy (hunk 1 above)
Comment (cdancy) [reply src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy]: eehhh ... I would say lets wait until something arises to do that IMO. This is simple and straightforward and folks can easily digest what is/is-not going on fairly easy just be looking at files on disk.

Comment (bmuschko) [reply src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy]: Happy to keep it as is. I don't think using Base64 would me more complex and could be decoded if needed.

```
Base64.getEncoder().encodeToString(path.getBytes("utf-8"))
```

**Comment by bmuschko** [comment]
Thanks for the pull request. I just pushed a new release containing the fix.

File: src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy (hunk 1 above)
Comment (bmuschko) [reply src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy]: The [`Base64` class](https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html) is just plain Java 8+.

Comment (cdancy) [reply src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy]: Didn't even know they had that in java8 which goes to show how long its been since I've needed to do this :)
